In [48]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

In [49]:
df = pd.read_csv('ML_ALL_benchmarks.csv')
df.dropna(inplace=True)
df.head()
column = ['clock','cpuScore','gpuScore','npuScore']
for val in column:
    df[val] = df[val] /df[val].max()
classes = df['cpuName']
# classes
df[:5]

,device,company,cpuName,cores,clock,cpuScore,gpuScore,npuScore
0,iPhone 13 Pro Max,Apple,A15 Bionic,6,1.000000,0.923001,0.799789,1.000000
1,iPhone 13 Pro,Apple,A15 Bionic,6,1.000000,0.919052,0.795567,0.995889
2,iPhone 13 mini,Apple,A15 Bionic,6,1.000000,0.912142,0.651654,0.994021
3,iPad Pro (12.9-inch 5th generation),Apple,M1,8,0.987616,1.000000,0.993666,0.992900
4,iPad Pro (11-inch 3rd generation),Apple,M1,8,0.987616,0.998026,1.000000,0.992526

In [50]:
df = df.drop(['company','device','cores'],axis=True)
# df.head()

In [51]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
  
df['cpuName']= label_encoder.fit_transform(df['cpuName'])

inp = df.drop('cpuName',axis=True)
inp
out = df['cpuName']
out

0       8
1       8
2       8
3      33
4      33
       ..
183    18
184    51
185    50
186    52
187    17
Name: cpuName, Length: 188, dtype: int32

In [52]:
classes

0          A15 Bionic
1          A15 Bionic
2          A15 Bionic
3                 M1
4                 M1
             ...
183       Exynos 8890
184    Snapdragon 810
185    Snapdragon 808
186    Snapdragon 835
187        Exynos 850
Name: cpuName, Length: 188, dtype: object

In [53]:
integerMapping=dict(zip(out,classes))
# integerMapping

In [58]:
X_train,X_test,Y_train,Y_test = train_test_split(inp,out,test_size=0.2)

In [61]:
X_test

        clock  cpuScore  gpuScore  npuScore
1    1.000000  0.919052  0.795567  0.995889
0    1.000000  0.923001  0.799789  1.000000
101  0.724458  0.352419  0.238213  0.143498
102  0.724458  0.349457  0.237861  0.142750
160  0.588235  0.152024  0.065799  0.046338
180  0.464396  0.134255  0.058761  0.029522
170  0.539319  0.118460  0.113652  0.037743
127  0.546749  0.191510  0.264954  0.109865
117  0.558514  0.222113  0.178747  0.120703
183  0.402477  0.131293  0.140746  0.026532
60   0.558514  0.375123  0.462702  0.259716
176  0.557276  0.153011  0.090077  0.032885
36   0.558514  0.416584  0.498593  0.327354
81   0.552632  0.310958  0.375088  0.199178
103  0.604954  0.373149  0.364180  0.142377
155  0.493189  0.154985  0.089374  0.048954
173  0.557276  0.149062  0.080929  0.036248
33   0.619195  0.277394  0.285011  0.408445
118  0.558514  0.220138  0.148487  0.120703
139  0.546749  0.213228  0.259676  0.103886
22   0.770898  0.671273  0.681914  0.506726
45   0.558514  0.428430  0.480296  0.288864
74   0.552632  0.314906  0.402885  0.220852
179  0.588235  0.153011  0.192822  0.029895
66   0.552632  0.313919  0.349754  0.248879
20   0.770898  0.685094  0.669599  0.528774
40   0.558514  0.352419  0.311752  0.302317
132  0.558514  0.221125  0.171006  0.106129
115  0.558514  0.365252  0.340605  0.121450
91   0.739938  0.402764  0.300141  0.158819
171  0.570588  0.132280  0.097115  0.037369
131  0.557276  0.303060  0.183673  0.106129
141  0.572446  0.275420  0.176636  0.101271
42   0.558514  0.392892  0.593948  0.294843
6    0.904025  0.887463  0.737157  0.942451
167  0.588235  0.156960  0.194581  0.038117
53   0.558514  0.373149  0.442646  0.267190
166  0.529102  0.125370  0.094652  0.039985